### ISSUE TITLE
Error: EPERM: operation not permitted

### ISSUE THREAD

**Issue by lefuturiste** [balena-io-modules/etcher-image-write#103]
Hi!

I run `npm run dev` on cmd (run as administrator) but I got this error.
I have verified with 'is-elevated' module but I got `true`.
I'm on windows.

This is my code : 
```js
const isElevated = require('is-elevated');
isElevated().then(elevated => {
  console.log(elevated);// return true in my case
});
const fs = require('fs')
var emitter = require('etcher-image-write').write({
  fd: fs.openSync('\\\\.\\E:', 'rs+'), // '\\\\.\\PHYSICALDRIVE1' in Windows, for example.
  device: '\\\\.\\E:',
  size: 2014314496
}, {
  stream: fs.createReadStream("D:\\Users\\mbess\\Documents\\2018-04-18-raspbian-stretch-lite.zip"),
  size: fs.statSync("D:\\Users\\mbess\\Documents\\2018-04-18-raspbian-stretch-lite.zip").size
}, {
  check: true
});

emitter.on('progress', (state) => {
  console.log(state);
});

emitter.on('error', (error) => {
  console.error(error);
});

emitter.on('done', (results) => {
  console.log('Success!');
});
```

That is the error : 

```
LandingPage.vue?1fd2:64 Error: EPERM: operation not permitted, write
    at Object.exports.usingStreaming (D:\workspace\thingmill.retrobox.desktop\node_modules\etcher-image-write\lib\write.js:114:10)
    at Object.exports.inferFromOptions (D:\workspace\thingmill.retrobox.desktop\node_modules\etcher-image-write\lib\write.js:210:18)
    at D:\workspace\thingmill.retrobox.desktop\node_modules\etcher-image-write\lib\index.js:133:18
    at <anonymous>
From previous event:
    at Object.exports.write (D:\workspace\thingmill.retrobox.desktop\node_modules\etcher-image-write\lib\index.js:132:31)
    at VueComponent.burn (webpack-internal:///10:19:45)
    at click (webpack-internal:///42:79:23)
    at invoker (webpack-internal:///0:2028:18)
    at HTMLButtonElement.fn._withTask.fn._withTask (webpack-internal:///0:1827:18)
```

**Comment by lurch** [comment]
Etcher's [documentation](https://github.com/resin-io/etcher/blob/master/docs/ARCHITECTURE.md) still needs updating, but Etcher [hasn't used this module](https://github.com/resin-io/etcher/pull/1671/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L57) since November 2017.

@jhermsmeier Should this `etcher-image-write` module be marked as deprecated / unsupported?

**Comment by lefuturiste** [comment]
@lurch Ok, How I can have a module to write

**Comment by lurch** [comment]
@lefuturiste I dunno, all I can suggest is looking at https://github.com/resin-io/etcher/pull/1671 :man_shrugging: 
@jhermsmeier Does he need to wait for the release of the "Etcher SDK" ?

**Comment by alexzace** [comment]
I oso facing the same error. It this issue fixed ?

**Comment by aethernet** [comment]
Hello,

Cleaning up here, this project is deprecated, and you should use https://github.com/balena-io-modules/etcher-sdk instead
